import { defineModule } from "../src/tscore/define.ts";
import { buildPersonalSiteConstants, loadReyneillSiteCore } from "../src/adapters/reyneill.ts";

const StringType = { kind: "primitive", name: "String" } as const;
const siteConstants = buildPersonalSiteConstants(loadReyneillSiteCore());

export default defineModule({
  name: "PersonalSiteCore",
  records: [
    {
      kind: "record",
      name: "PageRoute",
      fields: [
        { name: "path", type: StringType },
        { name: "label", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "SitePage",
      fields: [
        { name: "kind", type: { kind: "named", name: "PageKind" } },
        { name: "route", type: { kind: "named", name: "PageRoute" } },
        { name: "title", type: StringType },
        { name: "description", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "PublishPostPayload",
      fields: [
        { name: "title", type: StringType },
        { name: "slug", type: StringType },
        { name: "summary", type: StringType },
        { name: "content", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "PublishPostSuccess",
      fields: [
        { name: "ok", type: { kind: "primitive", name: "Bool" } },
        { name: "path", type: StringType },
        { name: "url", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "WritingManifestEntry",
      fields: [
        { name: "title", type: StringType },
        { name: "path", type: StringType },
        { name: "date", type: StringType },
        { name: "summary", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "WritingPostLookup",
      fields: [
        { name: "year", type: StringType },
        { name: "slug", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "SiteFooter",
      fields: [
        { name: "copyrightYear", type: StringType },
        { name: "ownerName", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "ContactLink",
      fields: [
        { name: "label", type: StringType },
        { name: "href", type: StringType },
        { name: "icon", type: StringType },
      ],
    },
    {
      kind: "record",
      name: "PrivatePageMetadata",
      fields: [
        { name: "title", type: StringType },
        { name: "description", type: StringType },
        { name: "robotsIndex", type: { kind: "primitive", name: "Bool" } },
        { name: "robotsFollow", type: { kind: "primitive", name: "Bool" } },
      ],
    },
    {
      kind: "record",
      name: "HomeProfile",
      fields: [
        { name: "headline", type: StringType },
        { name: "mission", type: StringType },
        { name: "rolePrefix", type: StringType },
        { name: "employerLabel", type: StringType },
        { name: "employerHref", type: StringType },
        { name: "roleSuffix", type: StringType },
        { name: "contactLead", type: StringType },
      ],
    },
  ],
  unions: [
    {
      kind: "taggedUnion",
      name: "PageKind",
      tag: "kind",
      variants: [
        { name: "home" },
        { name: "writing" },
        { name: "project" },
        { name: "admin" },
      ],
    },
    {
      kind: "taggedUnion",
      name: "PublishPostResult",
      tag: "status",
      variants: [
        {
          name: "success",
          fields: [
            { name: "ok", type: { kind: "primitive", name: "Bool" } },
            { name: "path", type: StringType },
            { name: "url", type: StringType },
          ],
        },
        {
          name: "error",
          fields: [{ name: "message", type: StringType }],
        },
      ],
    },
  ],
  constants: siteConstants,
  functions: [
    {
      kind: "function",
      name: "pageTitle",
      parameters: [{ name: "page", type: { kind: "named", name: "SitePage" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "title" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "title" }],
    },
    {
      kind: "function",
      name: "pageDescription",
      parameters: [{ name: "page", type: { kind: "named", name: "SitePage" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "description" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "description" }],
    },
    {
      kind: "function",
      name: "pageRoute",
      parameters: [{ name: "page", type: { kind: "named", name: "SitePage" } }],
      returns: { kind: "named", name: "PageRoute" },
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "route" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "route" }],
    },
    {
      kind: "function",
      name: "privatePageTitle",
      parameters: [{ name: "page", type: { kind: "named", name: "PrivatePageMetadata" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "title" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "title" }],
    },
    {
      kind: "function",
      name: "privatePageDescription",
      parameters: [{ name: "page", type: { kind: "named", name: "PrivatePageMetadata" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "description" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "description" }],
    },
    {
      kind: "function",
      name: "privatePageRobotsIndex",
      parameters: [{ name: "page", type: { kind: "named", name: "PrivatePageMetadata" } }],
      returns: { kind: "primitive", name: "Bool" },
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "robotsIndex" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "robotsIndex" }],
    },
    {
      kind: "function",
      name: "privatePageRobotsFollow",
      parameters: [{ name: "page", type: { kind: "named", name: "PrivatePageMetadata" } }],
      returns: { kind: "primitive", name: "Bool" },
      body: { kind: "field", target: { kind: "var", name: "page" }, field: "robotsFollow" },
      contracts: [{ kind: "returnsField", parameter: "page", field: "robotsFollow" }],
    },
    {
      kind: "function",
      name: "homeProfileHeadline",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "headline" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "headline" }],
    },
    {
      kind: "function",
      name: "homeProfileMission",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "mission" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "mission" }],
    },
    {
      kind: "function",
      name: "homeProfileRolePrefix",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "rolePrefix" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "rolePrefix" }],
    },
    {
      kind: "function",
      name: "homeProfileEmployerLabel",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "employerLabel" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "employerLabel" }],
    },
    {
      kind: "function",
      name: "homeProfileEmployerHref",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "employerHref" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "employerHref" }],
    },
    {
      kind: "function",
      name: "homeProfileRoleSuffix",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "roleSuffix" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "roleSuffix" }],
    },
    {
      kind: "function",
      name: "homeProfileContactLead",
      parameters: [{ name: "profile", type: { kind: "named", name: "HomeProfile" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "profile" }, field: "contactLead" },
      contracts: [{ kind: "returnsField", parameter: "profile", field: "contactLead" }],
    },
    {
      kind: "function",
      name: "routePath",
      parameters: [{ name: "route", type: { kind: "named", name: "PageRoute" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "route" }, field: "path" },
      contracts: [{ kind: "returnsField", parameter: "route", field: "path" }],
    },
    {
      kind: "function",
      name: "routeLabel",
      parameters: [{ name: "route", type: { kind: "named", name: "PageRoute" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "route" }, field: "label" },
      contracts: [{ kind: "returnsField", parameter: "route", field: "label" }],
    },
    {
      kind: "function",
      name: "footerCopyrightYear",
      parameters: [{ name: "footer", type: { kind: "named", name: "SiteFooter" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "footer" }, field: "copyrightYear" },
      contracts: [{ kind: "returnsField", parameter: "footer", field: "copyrightYear" }],
    },
    {
      kind: "function",
      name: "footerOwnerName",
      parameters: [{ name: "footer", type: { kind: "named", name: "SiteFooter" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "footer" }, field: "ownerName" },
      contracts: [{ kind: "returnsField", parameter: "footer", field: "ownerName" }],
    },
    {
      kind: "function",
      name: "contactLinkLabel",
      parameters: [{ name: "link", type: { kind: "named", name: "ContactLink" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "link" }, field: "label" },
      contracts: [{ kind: "returnsField", parameter: "link", field: "label" }],
    },
    {
      kind: "function",
      name: "contactLinkHref",
      parameters: [{ name: "link", type: { kind: "named", name: "ContactLink" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "link" }, field: "href" },
      contracts: [{ kind: "returnsField", parameter: "link", field: "href" }],
    },
    {
      kind: "function",
      name: "contactLinkIcon",
      parameters: [{ name: "link", type: { kind: "named", name: "ContactLink" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "link" }, field: "icon" },
      contracts: [{ kind: "returnsField", parameter: "link", field: "icon" }],
    },
    {
      kind: "function",
      name: "writingPublicPath",
      parameters: [
        { name: "year", type: StringType },
        { name: "datedSlug", type: StringType },
      ],
      returns: StringType,
      body: {
        kind: "concat",
        parts: [
          { kind: "string", value: "writing/" },
          { kind: "var", name: "year" },
          { kind: "string", value: "/" },
          { kind: "var", name: "datedSlug" },
          { kind: "string", value: "/" },
        ],
      },
      contracts: [{ kind: "returnsStartsWith", prefix: "writing/" }, { kind: "returnsEndsWith", suffix: "/" }],
    },
    {
      kind: "function",
      name: "writingPublicFilePath",
      parameters: [
        { name: "year", type: StringType },
        { name: "datedSlug", type: StringType },
      ],
      returns: StringType,
      body: {
        kind: "concat",
        parts: [
          { kind: "string", value: "web/public/writing/" },
          { kind: "var", name: "year" },
          { kind: "string", value: "/" },
          { kind: "var", name: "datedSlug" },
          { kind: "string", value: "/index.html" },
        ],
      },
      contracts: [{ kind: "returnsStartsWith", prefix: "web/public/writing/" }, { kind: "returnsEndsWith", suffix: "/index.html" }],
    },
    {
      kind: "function",
      name: "writingPublicIndexHref",
      parameters: [
        { name: "year", type: StringType },
        { name: "datedSlug", type: StringType },
      ],
      returns: StringType,
      body: {
        kind: "concat",
        parts: [
          { kind: "string", value: "/writing/" },
          { kind: "var", name: "year" },
          { kind: "string", value: "/" },
          { kind: "var", name: "datedSlug" },
          { kind: "string", value: "/index.html" },
        ],
      },
      contracts: [{ kind: "returnsStartsWith", prefix: "/" }, { kind: "returnsEndsWith", suffix: "/index.html" }],
    },
    {
      kind: "function",
      name: "publishedWritingTitle",
      parameters: [{ name: "title", type: StringType }],
      returns: StringType,
      body: {
        kind: "concat",
        parts: [
          { kind: "var", name: "title" },
          { kind: "string", value: " — Rey Neill" },
        ],
      },
      contracts: [{ kind: "returnsEndsWith", suffix: " — Rey Neill" }],
    },
    {
      kind: "function",
      name: "publishedWritingByline",
      parameters: [{ name: "name", type: StringType }],
      returns: StringType,
      body: {
        kind: "concat",
        parts: [
          { kind: "string", value: "— " },
          { kind: "var", name: "name" },
        ],
      },
      contracts: [{ kind: "returnsStartsWith", prefix: "— " }],
    },
    {
      kind: "function",
      name: "publishPostSuccess",
      parameters: [
        { name: "ok", type: { kind: "primitive", name: "Bool" } },
        { name: "path", type: StringType },
        { name: "url", type: StringType },
      ],
      returns: { kind: "named", name: "PublishPostSuccess" },
      body: {
        kind: "record",
        typeName: "PublishPostSuccess",
        fields: {
          ok: { kind: "var", name: "ok" },
          path: { kind: "var", name: "path" },
          url: { kind: "var", name: "url" },
        },
      },
      contracts: [{ kind: "recordConstructor" }],
    },
    {
      kind: "function",
      name: "writingManifestEntry",
      parameters: [
        { name: "title", type: StringType },
        { name: "path", type: StringType },
        { name: "date", type: StringType },
        { name: "summary", type: StringType },
      ],
      returns: { kind: "named", name: "WritingManifestEntry" },
      body: {
        kind: "record",
        typeName: "WritingManifestEntry",
        fields: {
          title: { kind: "var", name: "title" },
          path: { kind: "var", name: "path" },
          date: { kind: "var", name: "date" },
          summary: { kind: "var", name: "summary" },
        },
      },
      contracts: [{ kind: "recordConstructor" }],
    },
    {
      kind: "function",
      name: "writingManifestEntryTitle",
      parameters: [{ name: "entry", type: { kind: "named", name: "WritingManifestEntry" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "entry" }, field: "title" },
      contracts: [{ kind: "returnsField", parameter: "entry", field: "title" }],
    },
    {
      kind: "function",
      name: "writingManifestEntryPath",
      parameters: [{ name: "entry", type: { kind: "named", name: "WritingManifestEntry" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "entry" }, field: "path" },
      contracts: [{ kind: "returnsField", parameter: "entry", field: "path" }],
    },
    {
      kind: "function",
      name: "writingManifestEntryDate",
      parameters: [{ name: "entry", type: { kind: "named", name: "WritingManifestEntry" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "entry" }, field: "date" },
      contracts: [{ kind: "returnsField", parameter: "entry", field: "date" }],
    },
    {
      kind: "function",
      name: "writingManifestEntrySummary",
      parameters: [{ name: "entry", type: { kind: "named", name: "WritingManifestEntry" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "entry" }, field: "summary" },
      contracts: [{ kind: "returnsField", parameter: "entry", field: "summary" }],
    },
    {
      kind: "function",
      name: "writingPostLookup",
      parameters: [
        { name: "year", type: StringType },
        { name: "slug", type: StringType },
      ],
      returns: { kind: "named", name: "WritingPostLookup" },
      body: {
        kind: "record",
        typeName: "WritingPostLookup",
        fields: {
          year: { kind: "var", name: "year" },
          slug: { kind: "var", name: "slug" },
        },
      },
      contracts: [{ kind: "recordConstructor" }],
    },
    {
      kind: "function",
      name: "writingPostLookupYear",
      parameters: [{ name: "lookup", type: { kind: "named", name: "WritingPostLookup" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "lookup" }, field: "year" },
      contracts: [{ kind: "returnsField", parameter: "lookup", field: "year" }],
    },
    {
      kind: "function",
      name: "writingPostLookupSlug",
      parameters: [{ name: "lookup", type: { kind: "named", name: "WritingPostLookup" } }],
      returns: StringType,
      body: { kind: "field", target: { kind: "var", name: "lookup" }, field: "slug" },
      contracts: [{ kind: "returnsField", parameter: "lookup", field: "slug" }],
    },
    {
      kind: "function",
      name: "isWritingPostLookup",
      parameters: [{ name: "lookup", type: { kind: "named", name: "WritingPostLookup" } }],
      returns: { kind: "primitive", name: "Bool" },
      body: {
        kind: "and",
        terms: [
          {
            kind: "stringNonEmpty",
            target: { kind: "field", target: { kind: "var", name: "lookup" }, field: "year" },
          },
          {
            kind: "stringNonEmpty",
            target: { kind: "field", target: { kind: "var", name: "lookup" }, field: "slug" },
          },
        ],
      },
      contracts: [{ kind: "nonEmptyFieldsPredicate", parameter: "lookup", fields: ["year", "slug"] }],
    },
    {
      kind: "function",
      name: "publishSuccessResult",
      parameters: [{ name: "result", type: { kind: "named", name: "PublishPostSuccess" } }],
      returns: { kind: "named", name: "PublishPostResult" },
      body: {
        kind: "variant",
        unionName: "PublishPostResult",
        tag: "status",
        variant: "success",
        fields: {
          ok: { kind: "field", target: { kind: "var", name: "result" }, field: "ok" },
          path: { kind: "field", target: { kind: "var", name: "result" }, field: "path" },
          url: { kind: "field", target: { kind: "var", name: "result" }, field: "url" },
        },
      },
      contracts: [{ kind: "returnsVariant", variant: "success" }],
    },
    {
      kind: "function",
      name: "isPublishablePayload",
      parameters: [{ name: "payload", type: { kind: "named", name: "PublishPostPayload" } }],
      returns: { kind: "primitive", name: "Bool" },
      body: {
        kind: "and",
        terms: [
          {
            kind: "stringNonEmpty",
            target: { kind: "field", target: { kind: "var", name: "payload" }, field: "title" },
          },
          {
            kind: "stringNonEmpty",
            target: { kind: "field", target: { kind: "var", name: "payload" }, field: "slug" },
          },
        ],
      },
      contracts: [{ kind: "nonEmptyFieldsPredicate", parameter: "payload", fields: ["title", "slug"] }],
    },
    {
      kind: "function",
      name: "publishErrorResult",
      parameters: [{ name: "message", type: StringType }],
      returns: { kind: "named", name: "PublishPostResult" },
      body: {
        kind: "variant",
        unionName: "PublishPostResult",
        tag: "status",
        variant: "error",
        fields: {
          message: { kind: "var", name: "message" },
        },
      },
      contracts: [{ kind: "returnsVariant", variant: "error" }],
    },
    {
      kind: "function",
      name: "isPublishSuccess",
      parameters: [{ name: "result", type: { kind: "named", name: "PublishPostResult" } }],
      returns: { kind: "primitive", name: "Bool" },
      body: {
        kind: "isVariant",
        target: { kind: "var", name: "result" },
        unionName: "PublishPostResult",
        tag: "status",
        variant: "success",
      },
      contracts: [{ kind: "variantPredicate", parameter: "result", variant: "success" }],
    },
    {
      kind: "function",
      name: "isPublishError",
      parameters: [{ name: "result", type: { kind: "named", name: "PublishPostResult" } }],
      returns: { kind: "primitive", name: "Bool" },
      body: {
        kind: "isVariant",
        target: { kind: "var", name: "result" },
        unionName: "PublishPostResult",
        tag: "status",
        variant: "error",
      },
      contracts: [{ kind: "variantPredicate", parameter: "result", variant: "error" }],
    },
  ],
  stateMachines: [
    {
      kind: "stateMachine",
      name: "publishTransition",
      stateName: "PublishState",
      actionName: "PublishAction",
      states: ["draft", "scheduled", "published", "archived"],
      actions: ["schedule", "publish", "archive", "edit"],
      transitions: [
        { from: "draft", action: "schedule", to: "scheduled" },
        { from: "draft", action: "publish", to: "published" },
        { from: "draft", action: "archive", to: "archived" },
        { from: "scheduled", action: "publish", to: "published" },
        { from: "scheduled", action: "archive", to: "archived" },
        { from: "published", action: "publish", to: "published" },
        { from: "published", action: "archive", to: "archived" },
      ],
      terminalStates: ["archived"],
    },
  ],
});
