import type { TSCoreExpr, TSCoreModule, TSCoreType } from "./types.ts";

export function emitTSCoreTypeScript(module: TSCoreModule): string {
  const context = {
    unions: new Map(module.unions.map((union) => [union.name, union])),
  };
  const sections = [
    header(module.name),
    ...module.records.map(emitRecord),
    ...module.unions.map(emitUnion),
    ...module.constants.map((constant) => {
      return `export const ${constant.name}: ${emitType(constant.type)} = ${emitExpr(constant.value, context)};\n`;
    }),
    ...module.functions.map((fn) => {
      const params = fn.parameters.map((parameter) => `${parameter.name}: ${emitType(parameter.type)}`).join(", ");
      return `export function ${fn.name}(${params}): ${emitFunctionReturnType(fn, context)} {\n  return ${emitExpr(fn.body, context)};\n}\n`;
    }),
    ...module.stateMachines.flatMap(emitStateMachine),
  ];

  return `${sections.filter(Boolean).join("\n")}\n`;
}

function header(moduleName: string): string {
  return `// Generated by Bip from TSCore module '${moduleName}'.\n// Do not edit this file directly.\n`;
}

function emitRecord(record: TSCoreModule["records"][number]): string {
  const fields = record.fields.map((field) => `  ${field.name}: ${emitType(field.type)};`).join("\n");
  return `export type ${record.name} = {\n${fields}\n};\n`;
}

function emitUnion(union: TSCoreModule["unions"][number]): string {
  const variants = union.variants.map((variant) => {
    const fields = variant.fields?.map((field) => `${field.name}: ${emitType(field.type)}`).join("; ");
    const fieldSuffix = fields ? `; ${fields}` : "";
    return `  | { ${union.tag}: "${variant.name}"${fieldSuffix} }`;
  });

  return `export type ${union.name} =\n${variants.join("\n")};\n`;
}

function emitStateMachine(machine: TSCoreModule["stateMachines"][number]): string[] {
  const stateType = `export type ${machine.stateName} = ${machine.states.map((state) => `"${state}"`).join(" | ")};\n`;
  const actionType = `export type ${machine.actionName} = ${machine.actions.map((action) => `"${action}"`).join(" | ")};\n`;
  const cases = machine.transitions.map((transition) => {
    return `    case "${transition.from}:${transition.action}":\n      return "${transition.to}";`;
  });
  const reducer = `export function ${machine.name}(state: ${machine.stateName}, action: ${machine.actionName}): ${machine.stateName} {\n  switch (\`\${state}:\${action}\`) {\n${cases.join("\n")}\n    default:\n      return state;\n  }\n}\n`;
  const guardCases = machine.transitions.map((transition) => {
    return `    case "${transition.from}:${transition.action}":\n      return true;`;
  });
  const guard = `export function ${stateMachineGuardName(machine)}(state: ${machine.stateName}, action: ${machine.actionName}): boolean {\n  switch (\`\${state}:\${action}\`) {\n${guardCases.join("\n")}\n    default:\n      return false;\n  }\n}\n`;

  return [stateType, actionType, reducer, guard];
}

function stateMachineGuardName(machine: TSCoreModule["stateMachines"][number]): string {
  return `can${machine.name.slice(0, 1).toUpperCase()}${machine.name.slice(1)}`;
}

function emitFunctionReturnType(
  fn: TSCoreModule["functions"][number],
  context: { unions: Map<string, TSCoreModule["unions"][number]> },
): string {
  const variantPredicate = fn.contracts?.find((contract) => contract.kind === "variantPredicate");
  const parameter = variantPredicate ? fn.parameters.find((candidate) => candidate.name === variantPredicate.parameter) : undefined;
  const unionName = parameter?.type.kind === "named" ? parameter.type.name : undefined;
  const union = unionName ? context.unions.get(unionName) : undefined;

  if (variantPredicate && parameter && union) {
    return `${parameter.name} is Extract<${union.name}, { ${union.tag}: ${JSON.stringify(variantPredicate.variant)} }>`;
  }

  return emitType(fn.returns);
}

function emitType(type: TSCoreType): string {
  if (type.kind === "primitive") {
    if (type.name === "String") {
      return "string";
    }

    if (type.name === "Bool") {
      return "boolean";
    }

    return "number";
  }

  if (type.kind === "array") {
    return `ReadonlyArray<${emitType(type.item)}>`;
  }

  return type.name;
}

function emitExpr(expr: TSCoreExpr, context: { unions: Map<string, TSCoreModule["unions"][number]> }): string {
  if (expr.kind === "var") {
    return expr.name;
  }

  if (expr.kind === "string") {
    return JSON.stringify(expr.value);
  }

  if (expr.kind === "bool") {
    return String(expr.value);
  }

  if (expr.kind === "nat") {
    return String(expr.value);
  }

  if (expr.kind === "variant") {
    const fields = Object.entries(expr.fields ?? {}).map(([field, value]) => `${field}: ${emitExpr(value, context)}`);
    return `{ ${[`${expr.tag}: ${JSON.stringify(expr.variant)}`, ...fields].join(", ")} }`;
  }

  if (expr.kind === "isVariant") {
    const union = context.unions.get(expr.unionName);
    const tag = union?.tag ?? expr.tag;
    return `${emitExpr(expr.target, context)}.${tag} === ${JSON.stringify(expr.variant)}`;
  }

  if (expr.kind === "stringNonEmpty") {
    return `${emitExpr(expr.target, context)} !== ""`;
  }

  if (expr.kind === "and") {
    return expr.terms.length > 0 ? expr.terms.map((term) => `(${emitExpr(term, context)})`).join(" && ") : "true";
  }

  if (expr.kind === "field") {
    return `${emitExpr(expr.target, context)}.${expr.field}`;
  }

  if (expr.kind === "array") {
    return `[${expr.items.map((item) => emitExpr(item, context)).join(", ")}]`;
  }

  if (expr.kind === "concat") {
    return expr.parts.map((part) => emitExpr(part, context)).join(" + ");
  }

  const fields = Object.entries(expr.fields).map(([field, value]) => `${field}: ${emitExpr(value, context)}`).join(", ");
  return `{ ${fields} }`;
}
